### ISSUE TITLE
P I and D settings

### ISSUE THREAD

**Issue by colinl** [tyrrellsystems/node-red-contrib-pid-controller#11]
Hi
Have you considered using engineering values for the control settings rather than mathematical ones? By that I mean instead of using a gain figure use a proportional band (which is the number of engineering units, degrees for example, that take the proportional term from 0 to 1),  also use a time value for the derivative term (in seconds) and similarly a time value for the integral. So if these are PropBand, Ti and Td and the process error now is e1 and that at the last sample was e0, with a time interval dt then the equation for the output power is
power = (1/PropBand) *  (error + Td*(e1-e2)/dt + integral*dt/Ti)

This equation is basically the same as yours but is much easier to tune as the settings have a meaning in the real world.  Note that the units of this equation are consistent, error, Td(e1-e2) and integral*dt/Ti are all in degrees (or whatever is being controlled) and when multiplied by 1/PropBand this gives a dimensionless output, which is as it should be.

Note also that with your equation a change in the gain term will have an effect on the frequency response of the loop as it changes the ratios between the P, I and D terms so if the gain is changed then it will be necessary to change the I and D settings accordingly in order to keep the frequency response the same.
Regards
Colin

**Comment by davidoc85** [comment]
I agree, it shouldn't involve a lot of work and would make more sense.
example section 3.Tuning: http://www.ni.com/white-paper/3782/en/

That way we can work with the following changed variables:
KP --> P
Ki --> Ti
Kd --> Td
as at the moment I have to calculate:
Ki=Kp/Ti
Kd=Kp*Td

Any comments?

**Comment by hardillb** [comment]
No, I'm not rewriting the PID node this close to the end of the project

**Comment by colinl** [comment]
@davidoc When I got no response here to my suggestion I went ahead and released my own PID node which you might find useful https://www.npmjs.com/package/node-red-contrib-pid

**Comment by hardillb** [comment]
@colinl This PID controller was written for a very specific project myself and @davidoc85 are involved with. That project is coming to an end and there really isn't time to change this implementation. While I think we should try and get down to 1 PID controller node rather than the 3 we have currently I'm not going to have any time to put into merging/consolidating features in the near future.

I'll be honest I glossed over your comment initially because it wasn't directly related to the project and by the time I got to it you'd already gone and written your own version so again it went to the back of the queue.
